export const Interests = [
  "Fitness",
  "Nutrition",
  "Mental Health",
  "Wellness",
  "Yoga",
  "Meditation",
  "Mindfulness",
  "Strength Training",
  "Cardio",
  "Healthy Eating",
  "Weight Loss",
  "Stress Management",
  "Sleep Hygiene",
  "Work-Life Balance",
  "Self-Care",
  "Personal Development",
  "Holistic Health",
];
