export const Colors = {
  text: "#2D3436",
  grayBg: "#E5E7EB",
  lightGray: "#F7F8FA",
  lightText: "#4B5563",
  gray: "#B2B2B2",
  primary: "#A29BFE",
  secondary: "#424242",
  background: "#f5f5f5",
  textPrimary: "#212121",
  textSecondary: "#757575",
  error: "#d32f2f",
  success: "#388e3c",
  warning: "#f57c00",
  info: "#0288d1",
  white: "#ffffff",
  black: "#000000",
  transparent: "rgba(0,0,0,0)",
  body: "#F8F9FE",
};
export const Spacing = {
  small: 8,
  medium: 16,
  large: 24,
  xLarge: 32,
};
export const Typography = {
  fontSizeSmall: 12,
  fontSizeMedium: 16,
  fontSizeLarge: 20,
  fontSizeXLarge: 24,
  fontFamilyRegular: "Poppins-Regular",
  fontFamilyBold: "Poppins-Bold",
  fontFamilyItalic: "Poppins-Italic",
  fontFamilyLight: "Poppins-Light",
  fontFamilyMedium: "Poppins-Medium",
  fontFamily: "Poppins",
  fontFamilyLightItalic: "Poppins-LightItalic",
  fontFamilyMediumItalic: "Poppins-MediumItalic",
  fontFamilyBoldItalic: "Poppins-BoldItalic",
  fontFamilyThin: "Poppins-Thin",
  fontFamilyThinItalic: "Poppins-ThinItalic",

  fontSizeHeading: 28,
  fontWeightLight: "300",
  fontWeightRegular: "400",
  fontWeightMedium: "500",
  fontWeightBold: "700",

  lineHeight: 1.5,
};
